### ISSUE TITLE
cannot POST json body

### ISSUE THREAD

**Issue by nullne** [beego/swagger#1]
Here is notation:

    // @Title newFormat
    // @Description add new log format
    // @Param content body body true "log format in json"
    // @Success 201 {object} models.log.LogFormat
    // @Failure 422 json format error or format error self
    // @router / [post]

From swaggger UI got this:

![screen shot 2016-01-14 at 10 53 10](https://cloud.githubusercontent.com/assets/6008447/12314550/1c1455f8-baad-11e5-9b93-439209841841.png)

click try and got this:

![screen shot 2016-01-14 at 10 53 23](https://cloud.githubusercontent.com/assets/6008447/12314554/1efffe34-baad-11e5-87f2-c6e55c640b41.png)

It seems that the request method is OPTIONS rather than POST, but why?

**Comment by astaxie** [comment]
swagger use the ajax to send the post request. This is the CORS problem.  

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS 

http://stackoverflow.com/questions/1099787/jquery-ajax-post-sending-options-as-request-method-in-firefox

**Comment by nullne** [comment]
@astaxie  thks
it worked as i access the swagger on 127.0.0.1 rather than localhost
