### ISSUE TITLE
Update to latest

### ISSUE THREAD

**Issue by julienkosinski** [beego/swagger#6]
Hello,

Could you please update all to the latest version to fix this annoying bug I have ? https://github.com/swagger-api/swagger-ui/issues/2923

After I tested to update all the files from the "dist" directory of swagger-api, the error remains (from the file provided in the linked issue). Yet, no error if we try the file with http://petstore.swagger.io/. 
Seems really strange for me.

Thank you very much !

**Comment by astaxie** [comment]
Do you know whether http://petstore.swagger.io/ use which version? and  "dist" directory of swagger-api use which version?

**Comment by julienkosinski** [comment]
Okay, sorry, was my mistake, latest version from "dist" directory (master branch) of swagger-api is working, and the bug is fixed, it's version 3.0.12.
In fact browser was keeping cache...

**Comment by astaxie** [comment]
So you mean 3.0.12 fix the issue. Beego current use 3.0.6 now

**Comment by julienkosinski** [comment]
Yes, 3.0.12 fix the issue, 3.0.6 has the issue.

**Comment by julienkosinski** [comment]
After further tests it seems that the new version introduced another bug. When trying to send a request to the API I get a `swagger-ui-bundle.js:74 Uncaught TypeError: Cannot read property 'operation' of undefined`.
The version that seems to work without bug is 3.0.4. With this one I have to declare `"basePath": "127.0.0.1:8080/v1"` to make it work locally because it does not detect host of the server.

I'm going to report bug on swagger-ui.

**Comment by julienkosinski** [comment]
3.0.13 of swagger-ui fix everything here :).

**Comment by astaxie** [comment]
just update to 3.0.13. please try again

**Comment by julienkosinski** [comment]
@astaxie Thanks! It works perfectly! Just a detail, release has been correctly updated but not the release note which is stayed on 3.0.6 (but it's 3.0.13). https://github.com/beego/swagger/releases

**Comment by astaxie** [comment]
yea, I just reuse the old tags. As it's hard code in bee

**Comment by julienkosinski** [comment]
Okay, thank you very much! :)
